// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/aos-dev/dm/models"
)

type CreateTask struct {
	Name    string             `json:"name"`
	Status  *models.TaskStatus `json:"status"`
	Type    models.TaskType    `json:"type"`
	Src     *models.Endpoint   `json:"src"`
	Dst     *models.Endpoint   `json:"dst"`
	Options interface{}        `json:"options"`
}

type DeleteTask struct {
	ID string `json:"id"`
}
