// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	// Job related RPCs.
	PollJob(ctx context.Context, in *PollJobRequest, opts ...grpc.CallOption) (Agent_PollJobClient, error)
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobReply, error)
	WaitJob(ctx context.Context, in *WaitJobRequest, opts ...grpc.CallOption) (*WaitJobReply, error)
	FinishJob(ctx context.Context, in *FinishJobRequest, opts ...grpc.CallOption) (*FinishJobReply, error)
	// Job metadata related RPCs.
	SetJobMetadata(ctx context.Context, in *SetJobMetadataRequest, opts ...grpc.CallOption) (*SetJobMetadataReply, error)
	GetJobMetadata(ctx context.Context, in *GetJobMetadataRequest, opts ...grpc.CallOption) (*GetJobMetadataReply, error)
	DeleteJobMetadata(ctx context.Context, in *DeleteJobMetadataRequest, opts ...grpc.CallOption) (*DeleteJobMetadataReply, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) PollJob(ctx context.Context, in *PollJobRequest, opts ...grpc.CallOption) (Agent_PollJobClient, error) {
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], "/agent.Agent/PollJob", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentPollJobClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Agent_PollJobClient interface {
	Recv() (*PollJobReply, error)
	grpc.ClientStream
}

type agentPollJobClient struct {
	grpc.ClientStream
}

func (x *agentPollJobClient) Recv() (*PollJobReply, error) {
	m := new(PollJobReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobReply, error) {
	out := new(CreateJobReply)
	err := c.cc.Invoke(ctx, "/agent.Agent/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) WaitJob(ctx context.Context, in *WaitJobRequest, opts ...grpc.CallOption) (*WaitJobReply, error) {
	out := new(WaitJobReply)
	err := c.cc.Invoke(ctx, "/agent.Agent/WaitJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) FinishJob(ctx context.Context, in *FinishJobRequest, opts ...grpc.CallOption) (*FinishJobReply, error) {
	out := new(FinishJobReply)
	err := c.cc.Invoke(ctx, "/agent.Agent/FinishJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SetJobMetadata(ctx context.Context, in *SetJobMetadataRequest, opts ...grpc.CallOption) (*SetJobMetadataReply, error) {
	out := new(SetJobMetadataReply)
	err := c.cc.Invoke(ctx, "/agent.Agent/SetJobMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetJobMetadata(ctx context.Context, in *GetJobMetadataRequest, opts ...grpc.CallOption) (*GetJobMetadataReply, error) {
	out := new(GetJobMetadataReply)
	err := c.cc.Invoke(ctx, "/agent.Agent/GetJobMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteJobMetadata(ctx context.Context, in *DeleteJobMetadataRequest, opts ...grpc.CallOption) (*DeleteJobMetadataReply, error) {
	out := new(DeleteJobMetadataReply)
	err := c.cc.Invoke(ctx, "/agent.Agent/DeleteJobMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility
type AgentServer interface {
	// Job related RPCs.
	PollJob(*PollJobRequest, Agent_PollJobServer) error
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobReply, error)
	WaitJob(context.Context, *WaitJobRequest) (*WaitJobReply, error)
	FinishJob(context.Context, *FinishJobRequest) (*FinishJobReply, error)
	// Job metadata related RPCs.
	SetJobMetadata(context.Context, *SetJobMetadataRequest) (*SetJobMetadataReply, error)
	GetJobMetadata(context.Context, *GetJobMetadataRequest) (*GetJobMetadataReply, error)
	DeleteJobMetadata(context.Context, *DeleteJobMetadataRequest) (*DeleteJobMetadataReply, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (UnimplementedAgentServer) PollJob(*PollJobRequest, Agent_PollJobServer) error {
	return status.Errorf(codes.Unimplemented, "method PollJob not implemented")
}
func (UnimplementedAgentServer) CreateJob(context.Context, *CreateJobRequest) (*CreateJobReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedAgentServer) WaitJob(context.Context, *WaitJobRequest) (*WaitJobReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitJob not implemented")
}
func (UnimplementedAgentServer) FinishJob(context.Context, *FinishJobRequest) (*FinishJobReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishJob not implemented")
}
func (UnimplementedAgentServer) SetJobMetadata(context.Context, *SetJobMetadataRequest) (*SetJobMetadataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetJobMetadata not implemented")
}
func (UnimplementedAgentServer) GetJobMetadata(context.Context, *GetJobMetadataRequest) (*GetJobMetadataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobMetadata not implemented")
}
func (UnimplementedAgentServer) DeleteJobMetadata(context.Context, *DeleteJobMetadataRequest) (*DeleteJobMetadataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJobMetadata not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_PollJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PollJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).PollJob(m, &agentPollJobServer{stream})
}

type Agent_PollJobServer interface {
	Send(*PollJobReply) error
	grpc.ServerStream
}

type agentPollJobServer struct {
	grpc.ServerStream
}

func (x *agentPollJobServer) Send(m *PollJobReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Agent_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_WaitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).WaitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/WaitJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).WaitJob(ctx, req.(*WaitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_FinishJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).FinishJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/FinishJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).FinishJob(ctx, req.(*FinishJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SetJobMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetJobMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SetJobMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/SetJobMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SetJobMetadata(ctx, req.(*SetJobMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetJobMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetJobMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/GetJobMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetJobMetadata(ctx, req.(*GetJobMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteJobMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteJobMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/DeleteJobMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteJobMetadata(ctx, req.(*DeleteJobMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _Agent_CreateJob_Handler,
		},
		{
			MethodName: "WaitJob",
			Handler:    _Agent_WaitJob_Handler,
		},
		{
			MethodName: "FinishJob",
			Handler:    _Agent_FinishJob_Handler,
		},
		{
			MethodName: "SetJobMetadata",
			Handler:    _Agent_SetJobMetadata_Handler,
		},
		{
			MethodName: "GetJobMetadata",
			Handler:    _Agent_GetJobMetadata_Handler,
		},
		{
			MethodName: "DeleteJobMetadata",
			Handler:    _Agent_DeleteJobMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PollJob",
			Handler:       _Agent_PollJob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
