// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateTask struct {
	Name   string      `json:"name"`
	Status *TaskStatus `json:"status"`
}

type DeleteTask struct {
	ID string `json:"id"`
}
