// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StaffClient is the client API for Staff service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StaffClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	NextTask(ctx context.Context, in *NextTaskRequest, opts ...grpc.CallOption) (Staff_NextTaskClient, error)
	Elect(ctx context.Context, in *ElectRequest, opts ...grpc.CallOption) (*ElectReply, error)
}

type staffClient struct {
	cc grpc.ClientConnInterface
}

func NewStaffClient(cc grpc.ClientConnInterface) StaffClient {
	return &staffClient{cc}
}

func (c *staffClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/staff.Staff/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffClient) NextTask(ctx context.Context, in *NextTaskRequest, opts ...grpc.CallOption) (Staff_NextTaskClient, error) {
	stream, err := c.cc.NewStream(ctx, &Staff_ServiceDesc.Streams[0], "/staff.Staff/NextTask", opts...)
	if err != nil {
		return nil, err
	}
	x := &staffNextTaskClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Staff_NextTaskClient interface {
	Recv() (*NextTaskReply, error)
	grpc.ClientStream
}

type staffNextTaskClient struct {
	grpc.ClientStream
}

func (x *staffNextTaskClient) Recv() (*NextTaskReply, error) {
	m := new(NextTaskReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *staffClient) Elect(ctx context.Context, in *ElectRequest, opts ...grpc.CallOption) (*ElectReply, error) {
	out := new(ElectReply)
	err := c.cc.Invoke(ctx, "/staff.Staff/Elect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaffServer is the server API for Staff service.
// All implementations must embed UnimplementedStaffServer
// for forward compatibility
type StaffServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	NextTask(*NextTaskRequest, Staff_NextTaskServer) error
	Elect(context.Context, *ElectRequest) (*ElectReply, error)
	mustEmbedUnimplementedStaffServer()
}

// UnimplementedStaffServer must be embedded to have forward compatible implementations.
type UnimplementedStaffServer struct {
}

func (UnimplementedStaffServer) Register(context.Context, *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedStaffServer) NextTask(*NextTaskRequest, Staff_NextTaskServer) error {
	return status.Errorf(codes.Unimplemented, "method NextTask not implemented")
}
func (UnimplementedStaffServer) Elect(context.Context, *ElectRequest) (*ElectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Elect not implemented")
}
func (UnimplementedStaffServer) mustEmbedUnimplementedStaffServer() {}

// UnsafeStaffServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StaffServer will
// result in compilation errors.
type UnsafeStaffServer interface {
	mustEmbedUnimplementedStaffServer()
}

func RegisterStaffServer(s grpc.ServiceRegistrar, srv StaffServer) {
	s.RegisterService(&Staff_ServiceDesc, srv)
}

func _Staff_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staff.Staff/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Staff_NextTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NextTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StaffServer).NextTask(m, &staffNextTaskServer{stream})
}

type Staff_NextTaskServer interface {
	Send(*NextTaskReply) error
	grpc.ServerStream
}

type staffNextTaskServer struct {
	grpc.ServerStream
}

func (x *staffNextTaskServer) Send(m *NextTaskReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Staff_Elect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServer).Elect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staff.Staff/Elect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServer).Elect(ctx, req.(*ElectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Staff_ServiceDesc is the grpc.ServiceDesc for Staff service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Staff_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "staff.Staff",
	HandlerType: (*StaffServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Staff_Register_Handler,
		},
		{
			MethodName: "Elect",
			Handler:    _Staff_Elect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NextTask",
			Handler:       _Staff_NextTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "staff.proto",
}
